//! The Antigravity CLI setup system.
//!
//! This file is the harness's *facts*. Every command over them lives in
//! [`harness_runtime`], shared with the other setup systems, so a change to
//! behaviour lands once and a change to Antigravity CLI's surface lands here.
//!
//! # This target belongs to more than one product
//!
//! Every other harness here owns its home outright. Antigravity CLI does not:
//! it keeps its configuration *inside* `~/.gemini`, alongside Gemini CLI's own
//! files, split across two subdirectories -- `antigravity-cli/` for what belongs
//! to this CLI alone, and `config/` for the surfaces it shares.
//!
//! So the target named below is a directory this provider is a guest in. Two
//! things follow, and both are load-bearing rather than decorative:
//!
//! every namespace is prefixed, so nothing at the root of `~/.gemini` is ever
//! claimed -- most importantly `settings.json`, which is Gemini CLI's and not
//! this product's despite the name; and Gemini's credentials appear in
//! [`Harness::never_touch`] even though nothing would reach them anyway,
//! because a guard that only holds while the namespace list is correct is a
//! guard that fails the first time the list is edited.

use std::process::ExitCode;

mod software;

use harness_runtime::Harness;
use provider_v3::{ComponentKind, ProjectionKind};

/// Everything specific to Antigravity CLI, verified against
/// `antigravity-baseline.json`.
pub const ANTIGRAVITY: Harness = Harness {
    harness_id: "antigravity",
    provider_id: "antigravity-setup-system",
    version: env!("CARGO_PKG_VERSION"),
    product: "Antigravity CLI",
    vendor: "Google",
    documented_config_home: "~/.gemini",
    // Empty on purpose: the product documents no override for its home. An
    // invented variable name would read as a fact and be one nothing honours.
    config_home_env: "",
    control_directory: ".antigravity-setup-system",
    state_file: "NDDEV-ANTIGRAVITY-PROVIDER.json",
    predecessor_state_file: "NDDEV-ANTIGRAVITY-CLI-SETUP.json",
    profile_id: "antigravity/native-files/1",
    // Everything outside this list is a sibling overlay preserved verbatim --
    // which here includes another product's entire configuration.
    native_namespaces: &[
        "antigravity-cli/settings.json",
        "antigravity-cli/keybindings.json",
        "antigravity-cli/plugins",
        "config/plugins",
        "config/skills",
        "config/agents",
        "config/hooks.json",
        "config/mcp_config.json",
    ],
    // Gemini CLI's own, not this product's. Never read, never written, and
    // never copied into a backup slot: a backup of someone else's credentials
    // is a leak with a schedule.
    never_touch: &[
        "settings.json",
        "oauth_creds.json",
        "google_accounts.json",
        "tmp",
    ],
    permission_profiles: &["default"],
    // No instruction and no command: the product documents both only at
    // workspace scope, under a project's `.agents/`, and this provider
    // configures a home rather than a checkout. Declaring either would offer a
    // route that resolves nowhere.
    component_kinds: &[
        ComponentKind::Skill,
        ComponentKind::Agent,
        ComponentKind::Hook,
        ComponentKind::Mcp,
        ComponentKind::Plugin,
        ComponentKind::Setting,
    ],
    projection_kinds: &[ProjectionKind::NativeFiles, ProjectionKind::Plugin],
    max_files: 8192,
    max_bytes: 64 * 1024 * 1024,
    kit_identity: include_str!("../../../provider-kit/v3/KIT-IDENTITY.json"),
    // Generated by `build.rs` from this harness's `setups/` directory, so the
    // binary carries the catalog it is named after instead of hoping to find
    // one on a disk it was never shipped to.
    embedded_setups: include!(concat!(env!("OUT_DIR"), "/embedded_setups.rs")),
    software: Some(software::SOFTWARE),
};

fn main() -> ExitCode {
    harness_runtime::run(&ANTIGRAVITY, std::env::args().skip(1).collect())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::panic)]

    use super::*;

    /// The directory name this harness's setups live under in the workspace.
    const TOOL: &str = "antigravity";
    /// The declaration under test, named once so the shared test below reads
    /// the same in all seven crates.
    const HARNESS: Harness = ANTIGRAVITY;

    /// `build.rs` put the whole catalog in, under the paths it will be read by.
    ///
    /// This does **not** test for staleness, and an earlier version of this
    /// comment claimed it did. It cannot: `build.rs` declares
    /// `rerun-if-changed` on the catalog directory, so editing a setup rebuilds
    /// the table before this runs, and the test would be comparing the tree
    /// with itself. Observed — a deliberately edited setup left it green.
    ///
    /// What it does test is the build script, against a walk written
    /// independently of it: every file present, none invented, bytes exact, and
    /// paths relative and slash-separated. That last one is the one that would
    /// really break — `join("/")` is the only reason these keys are usable on
    /// Windows, and a path built with the platform separator would still look
    /// perfectly correct in the generated source.
    #[test]
    fn the_catalog_this_binary_carries_is_the_one_in_the_tree() {
        let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        // The workspace holds one directory per harness; a rendered public tree
        // ships one harness and holds it flat. Same two candidates `build.rs`
        // chooses between, asked the same way.
        let root = manifest.join("../../setups").join(TOOL);
        let root = if root.is_dir() {
            root
        } else {
            manifest.join("../../setups")
        };

        // Only the setup directories, which is what the reader lists and what
        // `build.rs` embeds. A rendered public tree also carries a
        // `setups/README.md` at the catalog root, which belongs to no setup.
        let mut on_disk = Vec::new();
        let mut stack: Vec<std::path::PathBuf> = std::fs::read_dir(&root)
            .unwrap()
            .map(|entry| entry.unwrap().path())
            .filter(|path| path.join("setup.json").is_file())
            .collect();
        while let Some(directory) = stack.pop() {
            for entry in std::fs::read_dir(&directory).unwrap() {
                let path = entry.unwrap().path();
                if path.is_dir() {
                    stack.push(path);
                } else {
                    on_disk.push(path);
                }
            }
        }

        assert_eq!(
            HARNESS.embedded_setups.len(),
            on_disk.len(),
            "the binary carries {} files and the tree holds {}",
            HARNESS.embedded_setups.len(),
            on_disk.len()
        );

        for (relative, bytes) in HARNESS.embedded_setups {
            assert!(
                !relative.contains('\\') && !relative.starts_with('/'),
                "{relative:?} is not a relative slash path; a key built with the \
                 platform separator reads correctly on Unix and finds nothing on Windows"
            );
            let path = root.join(relative);
            let found = std::fs::read(&path)
                .unwrap_or_else(|e| panic!("{relative} is compiled in but not in the tree: {e}"));
            assert_eq!(
                &found, bytes,
                "{relative} differs between the binary and the tree"
            );
        }
    }

    #[test]
    fn the_declaration_is_valid_and_names_this_host() {
        let info = ANTIGRAVITY.provider_info().unwrap();
        assert_eq!(info.provider_id, env!("CARGO_PKG_NAME"));
        assert_eq!(info.harness_id, "antigravity");
        assert_eq!(info.protocol_version, 3);
        assert!(info.supports_this_host());
    }

    #[test]
    fn no_namespace_is_both_owned_and_disclaimed() {
        for name in ANTIGRAVITY.never_touch {
            assert!(
                !ANTIGRAVITY.native_namespaces.contains(name),
                "{name} is claimed and disclaimed"
            );
        }
    }

    #[test]
    fn the_baseline_this_harness_cites_is_present_and_readable() {
        // The facts above are transcribed from it; a build whose baseline is
        // missing has no evidence for what it claims to own.
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../references/antigravity-baseline.json");
        let value: serde_json::Value =
            serde_json::from_slice(&std::fs::read(path).unwrap()).unwrap();
        assert!(value.is_object());
    }

    #[test]
    fn the_control_directory_and_state_file_are_provider_owned_not_product_owned() {
        assert!(ANTIGRAVITY.control_directory.contains("setup-system"));
        assert!(ANTIGRAVITY.state_file.starts_with("NDDEV-"));
        assert!(
            !ANTIGRAVITY
                .native_namespaces
                .contains(&ANTIGRAVITY.state_file)
        );
    }

    #[test]
    fn nothing_at_the_root_of_the_shared_home_is_claimed() {
        // The whole reason this harness is safe to point at `~/.gemini` is that
        // every namespace names a subdirectory. A root-level entry would claim a
        // file belonging to a product this provider knows nothing about, and
        // `remove` would then delete it.
        for namespace in ANTIGRAVITY.native_namespaces {
            assert!(
                namespace.contains('/'),
                "{namespace} sits at the root of a home shared with Gemini CLI"
            );
        }
    }

    #[test]
    fn the_two_settings_documents_are_told_apart_by_path_not_by_name() {
        // `settings.json` is Gemini CLI's; `antigravity-cli/settings.json` is
        // this product's. They share a basename, so only the prefix separates
        // them -- and this asserts the separation still exists.
        assert!(ANTIGRAVITY.never_touch.contains(&"settings.json"));
        assert!(
            ANTIGRAVITY
                .native_namespaces
                .contains(&"antigravity-cli/settings.json")
        );
    }
}
